name=CH462x
version=1.0.0
author=ReP64
maintainer=ReP64
sentence=Arduino library for CH462 LCD driver.
paragraph=Library for the WCH CH462 LCD display driver.
category=Display
url=https://github.com/ReP64/CH462x
architectures=*
